//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Contracts.MessageValid {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageCommons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageCommons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Contracts.MessageValid.MessageCommons", typeof(MessageCommons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} al registar {1}.
        /// </summary>
        public static string al_registar {
            get {
                return ResourceManager.GetString("al_registar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se establecio el estado de autenticacion en {0}()..
        /// </summary>
        public static string AuthStateNoSetPersist {
            get {
                return ResourceManager.GetString("AuthStateNoSetPersist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener el registro.
        /// </summary>
        public static string ErrorEntity {
            get {
                return ResourceManager.GetString("ErrorEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario o Password incorrectos o el usuario no se encuentra registrado.
        /// </summary>
        public static string ErrorLogin {
            get {
                return ResourceManager.GetString("ErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al ejecutar la operacion.
        /// </summary>
        public static string ErrorOperation {
            get {
                return ResourceManager.GetString("ErrorOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener la lista solicitada.
        /// </summary>
        public static string ErrorQuery {
            get {
                return ResourceManager.GetString("ErrorQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha debe ser mayor a la fecha actual.
        /// </summary>
        public static string fechamayor {
            get {
                return ResourceManager.GetString("fechamayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar una dirección de correo electrónico válida..
        /// </summary>
        public static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo no puede tener mas de {0} caracteres.
        /// </summary>
        public static string maxlenght {
            get {
                return ResourceManager.GetString("maxlenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontrol el registro solicitado.
        /// </summary>
        public static string NoDataEntity {
            get {
                return ResourceManager.GetString("NoDataEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron registros con la consulta solicitada.
        /// </summary>
        public static string NoDataQuery {
            get {
                return ResourceManager.GetString("NoDataQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} es un requisito obligatorio.
        /// </summary>
        public static string nullorempty {
            get {
                return ResourceManager.GetString("nullorempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe defenir una definicion de validacion (Objeto o JwtToken o ObjetoLista).
        /// </summary>
        public static string ResultAccionNull {
            get {
                return ResourceManager.GetString("ResultAccionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to el parametro de validacion ({0}) ya se inicializo, no puede tener dos objetos de validacion.
        /// </summary>
        public static string ResultAccionValida {
            get {
                return ResourceManager.GetString("ResultAccionValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se obtuvo el registro correctamente.
        /// </summary>
        public static string SuccessEntity {
            get {
                return ResourceManager.GetString("SuccessEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticacion de usuario correcta.
        /// </summary>
        public static string SuccessLogin {
            get {
                return ResourceManager.GetString("SuccessLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacion completada correctamente.
        /// </summary>
        public static string SuccessOperation {
            get {
                return ResourceManager.GetString("SuccessOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado obtenido correctamente.
        /// </summary>
        public static string SuccessQuery {
            get {
                return ResourceManager.GetString("SuccessQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar una URL válida..
        /// </summary>
        public static string url {
            get {
                return ResourceManager.GetString("url", resourceCulture);
            }
        }
    }
}
